language: python
cache: pip
python:
  - "3.5"
  - "3.6"
install: "make"
script:
  # Create empty secrets file. Its contents are not used by the test suite.
  - cp .travis/secrets.json.sample secrets.json
  - make test
notifications:
  email: false
